website:
    resource: "@WebsiteBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: '%app.locales%'

cpanel:
    resource: "@CpanelBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api
