website:
    resource: "@WebsiteBundle/Resources/config/routing.yml"
    prefix:   /

cpanel:
    resource: "@CpanelBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /
